services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          memory: 256M
